modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT License"
issueTrackerURL = "https://github.com/darkorg69/betterdurability/issues"

[[mods]]
modId = "betterdurability"
version = "${file.jarVersion}"
displayName = "Better Durability"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/betterdurability"
logoFile = "betterdurability.png"
credits = "Thanks for this mod goes to Java and the Forge team."
authors = "Darkorg"
#displayTest="MATCH_VERSION"
description = '''A mod to prevent your precious tools from breaking!'''

[[dependencies.betterdurability]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterdurability]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
