modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT License"
issueTrackerURL = "https://github.com/darkorg69/betterdurability/issues"

[[mods]]
modId = "betterdurability"
version = "1.18-1.0.0"
displayName = "BetterDurability"
#updateJSONURL=""
displayURL = "https://www.curseforge.com/minecraft/mc-mods/betterdurability"
logoFile = "betterdurability.png"
credits = "Thanks for this mod goes to Java and the Forge Team"
authors = "Darkorg"
description = '''A mod to prevent your precious tools from breaking!'''

[[dependencies.betterdurability]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterdurability]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,1.19)"
ordering = "NONE"
side = "BOTH"
