modLoader = "javafml"
loaderVersion = "[42,)"
license = "MIT License"
issueTrackerURL = "https://github.com/darkorg69/betterdurability/issues"

[[mods]]
modId = "betterdurability"
version = "${file.jarVersion}"
displayName = "Better Durability"
#updateJSONURL=""
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile = "examplemod.png" #optional
# A text field displayed in the mod UI
credits = "Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors = "Love, Cheese and small house plants" #optional
#displayTest="MATCH_VERSION"
description = ''''''

[[dependencies.betterdurability]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterdurability]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,1.20)"
ordering = "NONE"
side = "BOTH"
